In [70]:
%matplotlib inline
import numpy as np
import random as rnd
import matplotlib.pyplot as plt
import matplotlib.mlab as mlab
import collections
import itertools
import sys
import math
import scipy
import scipy.linalg
from pylab import *
from mpl_toolkits.mplot3d import Axes3D

In [2]:
b = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
np.linalg.det(b)

59.999999999999986

In [3]:
b = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
np.linalg.inv(b)

array([[-0.8       ,  0.1       ,  0.2       ],
       [ 0.1       , -0.2       ,  0.1       ],
       [ 0.53333333,  0.1       , -0.13333333]])

In [10]:
b = np.array([[1, -1, 2, -2], [2, -2, 4, -4], [3, -3, 6, -6], [4, -4, 8, -8]])
np.linalg.matrix_rank(b)           

1

In [12]:
np.inner([1,5],[2,8])

42

Смешанное произведение векторов (1,5,0) (2,8,7) (7, 1.5, 3)

In [15]:
a = np.array([1, 5, 0])
b = np.array([2, 8, 7])
c = np.array([7, 1.5, 3])

np.inner(np.cross(a,b), c)


228.5

Раздел "Ввведние в высшую математику"

1. Решите линейную систему

In [17]:
a = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
b = np.array([12, 2, 1])
np.linalg.solve(a, b)

array([-9.2       ,  0.9       ,  6.46666667])

In [20]:
a = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
b = np.array([12, 2, 1])
a1 = np.linalg.inv(a)
np.dot(a1, b)

array([-9.2       ,  0.9       ,  6.46666667])

2. Найдите псевдорешение:

In [23]:
a = np.array([[1, 2, -1], [3, -4, 0], [8, -5, 2], [2, 0, -5], [11, 4, -7]])
b = np.array([1, 7, 12, 7, 15])
np.linalg.lstsq(a, b)

<ipython-input-23-9b9e2ce61f2e>:3: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  np.linalg.lstsq(a, b)


(array([ 1.13919353, -0.90498444, -0.9009803 ]),
 array([0.71523211]),
 3,
 array([15.2817306 ,  9.59852942,  3.65197794]))

3. Сколько решений имеет линейная система:

In [45]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[12, 2, 1]])
c = np.concatenate((a,b.T), axis=1)
print(c)
np.linalg.matrix_rank(a), np.linalg.matrix_rank(c)

[[ 1  2  3 12]
 [ 4  5  6  2]
 [ 7  8  9  1]]


(2, 3)

In [49]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[0, 0, 0]])
c = np.concatenate((a,b.T), axis=1)
print(c)
np.linalg.matrix_rank(a), np.linalg.matrix_rank(c)

[[1 2 3 0]
 [4 5 6 0]
 [7 8 9 0]]


(2, 2)

In [61]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([0, 0, 0])
print(np.linalg.solve(a, b))
np.linalg.lstsq(a, b)

[ 0.  0. -0.]


<ipython-input-61-ef0ebe75714f>:4: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  np.linalg.lstsq(a, b)


(array([0., 0., 0.]),
 array([], dtype=float64),
 2,
 array([1.68481034e+01, 1.06836951e+00, 1.40266540e-16]))

4. Вычислите LU-разложение матрицы:


In [69]:
a = np.array([[1, 2, 3], [2, 16, 21], [4, 28, 73]])
p, l, u = scipy.linalg.lu(a)

print(p)
print(l)
print(u)

print(np.dot(p,a)- np.dot(l,u))

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]
[[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]
[[ -2. -12. -52.]
 [  3.  26.  70.]
 [ -1. -14. -18.]]


5. Найдите нормальное псевдорешение недоопределенной системы:

In [71]:
a = np.array([[1, 2, -1], [8, -5, 2]])
b = np.array([1, 12])
np.linalg.lstsq(a, b)

<ipython-input-71-50e764e457d7>:3: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  np.linalg.lstsq(a, b)


(array([ 1.38191882, -0.18081181,  0.0202952 ]),
 array([], dtype=float64),
 2,
 array([9.65316119, 2.41173777]))

6. Найдите одно из псевдорешений вырожденной системы:

In [74]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([2, 5, 11])
q, r = np.linalg.qr(a)

print(a)
print(q)
print(r)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-0.12309149  0.90453403  0.40824829]
 [-0.49236596  0.30151134 -0.81649658]
 [-0.86164044 -0.30151134  0.40824829]]
[[-8.12403840e+00 -9.60113630e+00 -1.10782342e+01]
 [ 0.00000000e+00  9.04534034e-01  1.80906807e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.11164740e-15]]


In [75]:
np.dot(q,r)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [81]:
r1 = r[:2, :2]
b1 = np.dot(np.transpose(q), b)[:2]
x1 = np.linalg.solve(r1, b1)
x = np.append(x1, 0)
np.linalg.norm(x)

1.4999999999999893

In [82]:
np.linalg.lstsq(a, b)

<ipython-input-82-6a14bdfc5560>:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  np.linalg.lstsq(a, b)


(array([ 1.25,  0.5 , -0.25]),
 array([], dtype=float64),
 2,
 array([1.68481034e+01, 1.06836951e+00, 1.40266540e-16]))